### ISSUE TITLE
Provide save image option.

### ISSUE THREAD

**Issue by FlaviusHouk** [FlaviusHouk/Dali#4]
Opened images might be saved in some location in different formats (jpeg, bmp, png).

**Comment by KudriavtsevAndrii** [comment]
@FlaviusHouk, I think, we need to move this to the version 0.2

**Comment by FlaviusHouk** [comment]
What about subclasses of [this class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.bitmapencoder?view=netframework-4.8)?

**Comment by KudriavtsevAndrii** [comment]
In simple - those classes are wrappers on [IWIC](https://docs.microsoft.com/en-us/windows/win32/wic/-wic-about-windows-imaging-codec) ecoders, I agree it can be used for a saving images, but in v0.1 we don't have functionality for manipulationg on images, so we have no reason to save them.

**Comment by KudriavtsevAndrii** [comment]
Oh, nevermind, I just saw  a new drag and drop support feature, so we need to modify existing design templates.

**Comment by FlaviusHouk** [comment]
Implemented opportunity to save, but this area requires refactoring in future.
