### ISSUE TITLE
Investigate options to translate keyboard input between windows or using global hotkes.

### ISSUE THREAD

**Issue by FlaviusHouk** [FlaviusHouk/Dali#5]
Semitransparent window should not receive keyboard and mouse input. It shoulo be possible to translate input to other window and have opportunity to switch input modes.

**Comment by KudriavtsevAndrii** [comment]
I think, we need to use global hot registration/unregistration, I found some interesting [example](https://www.fluxbytes.com/csharp/how-to-register-a-global-hotkey-for-your-application-in-c/). I going to implement(and test) it tomorrow.

**Comment by KudriavtsevAndrii** [comment]
Needed functionality successfully added to the solution.
